# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\workingSpace\python\card_image_replacer\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(922, 520)
        Form.setMinimumSize(QtCore.QSize(922, 520))
        Form.setMaximumSize(QtCore.QSize(922, 520))
        Form.setAcceptDrops(True)
        self.filename = QtWidgets.QLineEdit(Form)
        self.filename.setGeometry(QtCore.QRect(650, 400, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filename.setFont(font)
        self.filename.setStyleSheet("padding-left:7%;")
        self.filename.setObjectName("filename")
        self.saveLabel = QtWidgets.QLabel(Form)
        self.saveLabel.setGeometry(QtCore.QRect(700, 490, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.saveLabel.setFont(font)
        self.saveLabel.setStyleSheet("color: rgb(69, 207, 0);")
        self.saveLabel.setText("")
        self.saveLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.saveLabel.setObjectName("saveLabel")
        self.creditLabel = QtWidgets.QLabel(Form)
        self.creditLabel.setGeometry(QtCore.QRect(830, 500, 91, 16))
        self.creditLabel.setObjectName("creditLabel")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 851, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(90)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 410, 521, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectCard = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.selectCard.setFont(font)
        self.selectCard.setObjectName("selectCard")
        self.horizontalLayout.addWidget(self.selectCard)
        self.selectReplaceImage = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        self.selectReplaceImage.setFont(font)
        self.selectReplaceImage.setObjectName("selectReplaceImage")
        self.horizontalLayout.addWidget(self.selectReplaceImage)
        self.exportBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        self.exportBtn.setFont(font)
        self.exportBtn.setObjectName("exportBtn")
        self.horizontalLayout.addWidget(self.exportBtn)
        self.clearBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(29)
        self.clearBtn.setFont(font)
        self.clearBtn.setObjectName("clearBtn")
        self.horizontalLayout.addWidget(self.clearBtn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(640, 440, 241, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saveBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.saveBtn.setFont(font)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_2.addWidget(self.saveBtn)
        self.saveAsBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.saveAsBtn.setFont(font)
        self.saveAsBtn.setObjectName("saveAsBtn")
        self.horizontalLayout_2.addWidget(self.saveAsBtn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Card image replacer"))
        self.filename.setPlaceholderText(_translate("Form", "filename"))
        self.creditLabel.setText(_translate("Form", "created by Jirat.S"))
        self.selectCard.setText(_translate("Form", "SELECT\n"
"CARD"))
        self.selectReplaceImage.setText(_translate("Form", "SELECT\n"
"REPLACE IMAGE"))
        self.exportBtn.setText(_translate("Form", "EXPORT\n"
"ONLY IMAGE"))
        self.clearBtn.setText(_translate("Form", "CLEAR"))
        self.saveBtn.setText(_translate("Form", "SAVE"))
        self.saveAsBtn.setText(_translate("Form", "SAVE AS"))


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
